server:
  port: 8081
spring:
  application:
    name: dubbo-say-hello
  main:
    allow-bean-definition-overriding: true

dubbo:
  application:
    name: say-hello-provider
    qos-port: 33333
  registry:
    address: nacos://192.168.26.1:8848
    username: nacos
    password: nacos
  protocol:
    name: dubbo
    port: 9999
  scan:
    base-packages: com.hwt.service
